### ISSUE TITLE
Reduce error when selected bone has no keyframe

### ISSUE THREAD

**Issue by maniakid** [richard-roberts/SalientPosesMaya#21]
When bone has no keyframe,hit reduce button will throw error:
I was testing a zombie punching animation from mixamo,his left hand fingers has no keyframe at all.

```
# Traceback (most recent call last):
#   File "C:\Users\Ocean\Documents\maya\2018\scripts\SalientPoses\scripts\salient_menu.py", line 207, in do_reduce
#     self.save_animation(objects, start, end)
#   File "C:\Users\Ocean\Documents\maya\2018\scripts\SalientPoses\scripts\salient_menu.py", line 154, in save_animation
#     saved = SavedAnimation(objects, start, end)
#   File "C:\Users\Ocean\Documents\maya\2018\scripts\SalientPoses\scripts\salient_menu.py", line 26, in __init__
#     self.save()
#   File "C:\Users\Ocean\Documents\maya\2018\scripts\SalientPoses\scripts\salient_menu.py", line 35, in save
#     values = [cmds.keyframe(curve, time=(t, t), eval=True, query=True)[0] for t in times]
# TypeError: 'NoneType' object is not iterable
```

![image](https://user-images.githubusercontent.com/488200/47408094-7f8cda80-d790-11e8-99ed-33cce27c8332.png)

**Comment by richard-roberts** [comment]
Hi @maniakid, thanks for posting this issue. 

The bug seems to occur because the value of `times` variable is set to `None`, rather than being an empty list. I should have checked this more carefully before making the release. I've managed to fix this issue. Would you mind downloading the update below to confirm it's fixed? If it works for you, I'll update the release. 

Here's the update. Please download this [update.zip](https://github.com/richard-roberts/SalientPosesMaya/files/2510307/updatedScripts.zip) file, which is a compressed file containing an updated set of Python files (this is the code the runs the user interface in Maya). Once it's downloaded, please unzip and **replace** the files in the plug-ins scripts directory with these new ones. From there, try running the program again on the zombie example.

Thanks again for posting the issue!

**Comment by maniakid** [comment]
Hi Richard,I've sent you an E-mail about my test,please check it out.

**Comment by richard-roberts** [comment]
Hi again, thanks for testing that.

As per the email, there is one problem with the update: if no keyframes are present before reduction they appear after reduction, but then **are not** removed when `Undo` button is pressed.

I'll try fix this today and make an update!

**Comment by richard-roberts** [comment]
Not sure when I made this fix, but an error is now reported correctly and the undo feature works as expected.
